// cspell:disable
type Territory =
  | 'República de Chile'
  | 'Región de Valparaíso'
  | 'Provincia de San Antonio'
  | 'Provincia de Quillota'
  | 'Provincia de San Felipe'
  | 'Provincia de Los Andes'
  | 'Provincia de Petorca'
  | 'Provincia Marga Marga'
  | 'Provincia de Isla de Pascua'
  | 'Servicio de Salud Aconcagua'
  | 'Servicio de Salud Valparaíso San Antonio'
  | 'Servicio de Salud Viña del Mar Quillota'
  | 'Comuna de Valparaíso'
  | 'Comuna de Viña del Mar'
  | 'Comuna de Quintero'
  | 'Comuna de Puchuncaví'
  | 'Comuna de Casablanca'
  | 'Comuna de Concón'
  | 'Comuna de Juán Fernández'
  | 'Comuna de San Antonio'
  | 'Comuna de Santo Domingo'
  | 'Comuna de Cartagena'
  | 'Comuna de El Tabo'
  | 'Comuna de El Quisco'
  | 'Comuna de Algarrobo'
  | 'Comuna de Quillota'
  | 'Comuna de La Cruz'
  | 'Comuna de La Calera'
  | 'Comuna de Nogales'
  | 'Comuna de Hijuelas'
  | 'Comuna de San Felipe'
  | 'Comuna de Panquehue'
  | 'Comuna de Llay Llay'
  | 'Comuna de Catemu'
  | 'Comuna de Putaendo'
  | 'Comuna de Santa María'
  | 'Comuna de De Los Andes'
  | 'Comuna de Calle Larga'
  | 'Comuna de Rinconada'
  | 'Comuna de San Esteban'
  | 'Comuna de La Ligua'
  | 'Comuna de Zapallar'
  | 'Comuna de Papudo'
  | 'Comuna de Petorca'
  | 'Comuna de Cabildo'
  | 'Comuna de Quilpué'
  | 'Comuna de Villa Alemana'
  | 'Comuna de Limache'
  | 'Comuna de Olmué'
  | 'Comuna de Rapa Nui'
  | 'Provincia de Valparaíso'
  | 'Provincia de Marga Marga'
  | 'Mar de Chile'
  | 'Prefectura de Valparaíso'
  | 'Prefectura de Viña del Mar'
  | 'Prefectura de Aconcagua'
  | 'Prefectura Viña del Mar'
  | 'Prefectura Concón'
  | 'Prefectura San Antonio'
  | 'Prefectura Quillota'
  | 'Prefectura La Calera'
  | 'Prefectura San Felipe'
  | 'Prefectura Los Andes'
  | 'Prefectura La Ligua'
  | 'Prefectura Papudo'
  | 'Prefectura Quilpué'
  | 'Prefectura Villa Alemana'
  | 'Prefectura Limache'
  | 'Prefectura Isla de Pascua';

export default Territory;
